import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import Footer from "@/components/sections/footer";
import Header from "@/components/sections/header";
import ScrollIndicator from "@/components/elements/ScrollIndicator";
import Breadcrumbs from "@/components/sections/breadcrumbs";

const raleway = Raleway({
  subsets: ['latin'],
  variable: '--ralway',
  display: 'swap',
  weight: ["400", "700"]
});

export const metadata: Metadata = {
  title: "AZ & Partners | Accounting & Taxation in Paramatta",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${raleway.className}`}>
      <head>
        <link rel="icon" href="/next.svg" type="image/svg+xml" />
      </head>
      <body>
        <Header />
        <main>{children}</main>
        <Footer />
        <ScrollIndicator />
      </body>
    </html>
  );
}
